version: "3.8"

services:

  api:
    image: node:14
    restart: "no"
    user: node
    working_dir: /home/node/app
    volumes: 
      - .:/home/node/app
    ports:
      - "3000:3000"
    command: bash -c "npm i && npm run dev"
    environment:
      PGUSER: gqlserver
      PGHOST: db
      PGDATABASE: gqlserver-prod
      PGPASSWORD: root
      PGPORT: 5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: gqlserver
      POSTGRES_DB: gqlserver-prod
    volumes:
      - ./gqldata:/var/lib/postgresql/data
      - ./gqlserver_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  gqldata: