version: "3.8"

services:

  api:
    image: node:14
    restart: "no"
    user: node
    working_dir: /home/node/app
    volumes: 
      - .:/home/node/app
    ports:
      - "3000:3000"
    command: bash -c "npm i && npm run dev"
    environment:
      PGUSER: docker
      PGPASSWORD: docker
      PGHOST: db
      PGDATABASE: docker
      PGPORT: 5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - "gqldata:/var/lib/postgresql/data"
      - "./gqlserver_db.sql:/docker-entrypoint-initdb.d/gqlserver_db.sql"
    ports:
      - "5432:5432"

volumes:
  gqldata: